version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./file_automation:/app

  file_automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_automation
    volumes:
      - ./test_files:/app/test_files
      - ./sorted:/app/sorted
      - ./logs:/app/logs
    command: ["tail", "-f", "/dev/null"]

volumes:
  jenkins_home:

